version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - nuxt-network

  nuxt:
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
